src/Entity/MissionSensor.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ApiResource()
 * @ORM\Entity(repositoryClass="App\Repository\MissionSensorRepository")
 */
class MissionSensor
{
    use TimestampableEntity;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="UUID")
     * @ORM\Column(type="guid")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Mission", inversedBy="missionSensors")
     * @ORM\JoinColumn(nullable=false)
     */
    private $mission;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Sensor")
     * @ORM\JoinColumn(nullable=false)
     */
    private $sensor;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MissionSensorWarning", mappedBy="missionSensor", cascade={"persist"}, orphanRemoval=true)
     */
    private $sensorWarnings;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="boolean")
     */
    private $enabled = true;

    public function __construct()
    {
        $this->sensorWarnings = new ArrayCollection();
    }

    public function getId(): ?string
    {
        return $this->id;
    }

    public function getMission(): ?Mission
    {
        return $this->mission;
    }

    public function setMission(?Mission $mission): self
    {
        $this->mission = $mission;

        return $this;
    }

    public function getSensor(): ?Sensor
    {
        return $this->sensor;
    }

    public function setSensor(?Sensor $sensor): self
    {
        $this->sensor = $sensor;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEnabled(): ?bool
    {
        return $this->enabled;
    }

    public function setEnabled(bool $enabled): self
    {
        $this->enabled = $enabled;

        return $this;
    }

    /**
     * @return Collection|MissionSensorWarning[]
     */
    public function getSensorWarnings(): Collection
    {
        return $this->sensorWarnings;
    }

    public function addSensorWarning(MissionSensorWarning $sensorWarning): self
    {
        if (!$this->sensorWarnings->contains($sensorWarning)) {
            $this->sensorWarnings[] = $sensorWarning;
            $sensorWarning->setMissionSensor($this);
        }

        return $this;
    }

    public function removeSensorWarning(MissionSensorWarning $sensorWarning): self
    {
        if ($this->sensorWarnings->contains($sensorWarning)) {
            $this->sensorWarnings->removeElement($sensorWarning);
            // set the owning side to null (unless already changed)
            if ($sensorWarning->getMissionSensor() === $this) {
                $sensorWarning->setMissionSensor(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return sprintf('%s (%s)',
            $this->getSensor() ? $this->getSensor()->getId() : '',
            $this->getName()
        );
    }
}

src/Entity/Sensor.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Scorpio\Client;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Serializer\Annotation\Groups;
use whatwedo\SearchBundle\Annotation\Index;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SensorRepository")
 * @ApiResource()
 */
class Sensor
{
    use TimestampableEntity;

    /**
     * @ORM\Id()
     * @ORM\Column(type="string")
     * @Groups({"sensor", "measurement_read", "mission_log_entry_read"})
     * @Index()
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Index()
     */
    private $type;

    /**
     * @ORM\Column(type="json")
     */
    private $data = [];

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $metadata;

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $stream;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $streamId;

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $streamObservation;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $streamObservationId;

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $qoi;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $qoiId;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Index()
     */
    private $name;

    public function __toString(): string
    {
        return $this->getId() ?? self::class;
    }

    public function getId(): ?string
    {
        return $this->id;
    }

    public function setId(string $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getType(): ?string
    {
        if (null === $this->type && null !== $this->metadata) {
            $this->type = $this->metadata['type'] ?? null;
        }

        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getData(): ?array
    {
        return $this->data;
    }

    public function setData(array $data): self
    {
        $this->data = $data;

        return $this;
    }

    public function getMetadata(): ?array
    {
        return $this->metadata;
    }

    /**
     * @return Sensor
     */
    public function setMetadata(array $metadata): self
    {
        $this->metadata = $metadata;

        return $this;
    }

    public function getStream(): ?array
    {
        return $this->stream;
    }

    /**
     * @return Sensor
     */
    public function setStream(array $stream): self
    {
        $this->stream = $stream;
        $this->streamId = $stream['id'] ?? null;

        return $this;
    }

    public function getStreamObservation(): ?array
    {
        return $this->streamObservation;
    }

    /**
     * @return Sensor
     */
    public function setStreamObservation(array $streamObservation): self
    {
        $this->streamObservation = $streamObservation;
        $this->streamObservationId = $streamObservation['id'] ?? null;

        return $this;
    }

    public function getStreamObservationId(): ?string
    {
        return $this->streamObservationId;
    }

    public function getQoi(): ?array
    {
        return $this->qoi;
    }

    /**
     * @return Sensor
     */
    public function setQoi(array $qoi): self
    {
        $this->qoi = $qoi;
        $this->qoiId = $qoi['id'] ?? null;

        return $this;
    }

    public function getQoiId(): ?string
    {
        return $this->qoiId;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getIdentifier(): ?string
    {
        return $this->data[Client::ENTITY_ATTRIBUTE_IDENTIFIER]['value'] ?? null;
    }

    public function getObservationType(): ?string
    {
        return $this->data[Client::ENTITY_ATTRIBUTE_OBSERVES]['object'] ?? null;
    }

    public function getSensorData(): array
    {
        return [
            'name' => $this->getName(),
            'identifier' => $this->getIdentifier(),
            'observation_type' => $this->getObservationType(),
            'qoi' => $this->getQoi(),
        ];
    }
}

src/Form/Type/MissionSensorType.php
<?php

namespace App\Form\Type;

use App\Entity\MissionSensor;
use App\Entity\Sensor;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MissionSensorType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        /** @var Sensor $sensor */
        $sensor = $builder->getData()->getSensor();
        $builder
            ->add('sensor', EntityType::class, [
                'label' => $this->trans('Sensor'),
                'translation_domain' => false,
                'block_name' => 'sensor_details',
                'class' => Sensor::class,
                'choices' => [
                    $sensor->getId() => $sensor,
                ],
                'attr' => [
                    'readonly' => 'readonly',
                ],
            ])
            ->add('name', TextType::class, [
                'label' => $this->trans('Name'),
                'translation_domain' => false,
                'required' => false,
                'help' => $this->trans('Give the sensor a name for this mission'),
            ])
            ->add('enabled', CheckboxType::class, [
                'label' => $this->trans('Enabled'),
                'translation_domain' => false,
                'required' => false,
            ])
            ->add('sensorWarnings', CollectionType::class, [
                'label' => $this->trans('Sensor warnings'),
                'translation_domain' => false,
                'help' => $this->trans('Sensor warning can help you detect invalid data.'),
                'entry_type' => MissionSensorWarningType::class,
                'entry_options' => [
                    'label' => false,
                    'block_prefix' => 'mission_sensor_sensor_warning_item',
                ],
                'block_prefix' => 'mission_sensor_warning',
                'block_name' => 'sensor_warnings',
                'allow_add' => true,
                'allow_delete' => true,
                // Apparently this is needed to set mission_sensor_id correctly, but why?
                'by_reference' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => MissionSensor::class,
        ]);
    }
}

src/Controller/MissionSensorController.php
<?php

namespace App\Controller;

use App\Entity\Mission;
use App\Entity\MissionSensor;
use App\Form\Type\MissionSensorType;
use App\Repository\MissionSensorRepository;
use App\Scorpio\SensorManager;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * @Route("/mission/{mission}/sensor", name="mission_sensor_")
 */
class MissionSensorController extends AbstractController
{
    /**
     * @Route("/", name="index", methods={"GET"})
     */
    public function index(Mission $mission, MissionSensorRepository $missionSensorRepository): Response
    {
        return $this->render('mission_sensor/index.html.twig', [
            'mission' => $mission,
            'mission_sensors' => $missionSensorRepository->findByMission($mission),
        ]);
    }

    /**
     * @Route("/add", name="add", methods={"GET"})
     */
    public function add(Request $request, Mission $mission): Response
    {
        return $this->render('mission_sensor/add.html.twig', [
            'mission' => $mission,
        ]);
    }

    /**
     * @Route("/new", name="new", methods={"GET","POST"})
     */
    public function new(Request $request, Mission $mission, SensorManager $sensorManager, TranslatorInterface $translation): Response
    {
        $sensorId = $request->query->get('sensor') ?? '';
        try {
            $sensor = $sensorManager->getSensor($sensorId);
            $missionSensor = (new MissionSensor())
                ->setSensor($sensor);
            $mission->addMissionSensor($missionSensor);

            return $this->edit($request, $missionSensor);
        } catch (Exception $exception) {
            $this->addFlash('danger', $translation->trans('Error adding sensor %sensor% (Message: “%message%”)', [
                '%sensor%' => $sensorId,
                '%message%' => $exception->getMessage(),
            ]));

            return $this->redirectToRoute('mission_sensor_add', ['mission' => $mission->getId()]);
        }
    }

    /**
     * @Route("/search", name="search", methods={"GET"})
     */
    public function search(Request $request, Mission $mission, SensorManager $sensorManager): Response
    {
        $missionSensors = [];
        foreach ($mission->getMissionSensors() as $missionSensor) {
            $missionSensors[$missionSensor->getSensor()->getId()] = [
                'id' => $missionSensor->getId(),
                'name' => $missionSensor->getName(),
            ];
        }
        $options = [
            'mission_sensors' => $missionSensors,
            'query' => $request->query->all(),
        ];
        $sensors = $sensorManager->search($options);

        return new JsonResponse($sensors);
    }

    /**
     * @Route("/{id}", name="show", methods={"GET"})
     */
    public function show(MissionSensor $missionSensor): Response
    {
        return $this->render('mission_sensor/show.html.twig', [
            'mission_sensor' => $missionSensor,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="edit", methods={"GET","POST"})
     */
    public function edit(Request $request, MissionSensor $missionSensor): Response
    {
        $form = $this->createForm(MissionSensorType::class, $missionSensor);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($missionSensor);
            $em->flush();

            return $this->redirectToRoute('mission_show', ['id' => $missionSensor->getMission()->getId()]);
        }

        $deleteForm = null;

        if (null !== $missionSensor->getId()) {
            $deleteForm = $this->createFormBuilder()
                ->setMethod('DELETE')
                ->setAction($this->generateUrl('mission_sensor_delete', ['mission' => $missionSensor->getMission()->getId(), 'id' => $missionSensor->getId()]))
                ->getForm();
        }

        return $this->render('mission_sensor/edit.html.twig', [
            'mission_sensor' => $missionSensor,
            'form' => $form->createView(),
            'delete_form' => null !== $deleteForm ? $deleteForm->createView() : null,
        ]);
    }

    /**
     * @Route("/{id}", name="delete", methods={"DELETE"})
     */
    public function delete(Request $request, MissionSensor $missionSensor): Response
    {
        if ($this->isCsrfTokenValid('delete'.$missionSensor->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($missionSensor);
            $entityManager->flush();
        }

        return $this->redirectToRoute('mission_show', ['id' => $missionSensor->getMission()->getId()]);
    }
}

templates/mission_sensor/_delete_form.html.twig
<form method="post" action="{{ path('mission_sensor_delete', {mission: mission_sensor.mission.id, id: mission_sensor.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ mission_sensor.id) }}">
    <button class="btn">Delete</button>
</form>

templates/mission_sensor/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'Add mission sensor'|trans }}{% endblock %}

{% block content %}
    <div class="container-fluid bg-white">
        <article class="mission-sensor py-3">

            {% include '_nav_close.html.twig' with {'nav_path': path_from_referer('mission_show', {id: mission.id})} %}
            <h1>{{ 'Add mission sensor'|trans }}</h1>

            {% set options = {
                searchUrl: url('mission_sensor_search', {mission: mission.id}),
                addSensorUrl: url('mission_sensor_new', {mission: mission.id, sensor: '%sensor%'})|replace({('%'|url_encode): '%'}),
                editSensorUrl: url('mission_sensor_edit', {mission: mission.id, id: '%sensor%'})|replace({('%'|url_encode): '%'}),
                observationTypesUrl: url('api_data_observation_types'),
                } %}
            <div id="app" data-options="{{ options|json_encode }}">
                {{ 'Loading app …'|trans }}
            </div>
        </article>
    </div>
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('mission_sensor/add') }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('mission_sensor/add') }}
{% endblock %}

templates/mission_sensor/edit.html.twig
{% extends 'base.html.twig' %}

{% from 'mission/show.html.twig' import render_qoi %}

{% block title %}{{ 'Edit mission sensor'|trans }}{% endblock %}

{% block content %}
    {% set is_new_sensor = mission_sensor.id is null %}

    <div class="container-fluid bg-white">
        <article class="mission-sensor py-3">
            <h1>{{ is_new_sensor ? 'Create mission sensor'|trans : 'Edit mission sensor'|trans }}</h1>

            {{ form_start(form) }}
                {% set sensor = mission_sensor.sensor %}
                {% set missing_value = '👻' %}

                <div class="form-group row">
                    {{ form_label(form.sensor) }}
                    <div style="display: none">{{ form_widget(form.sensor) }}</div>

                    <div class="col-sm-10">
                        <div class="small bg-light">
                            <dl class="row">
                                <dt class="col-sm-3 mission-sensor-id sensor-id">{{ 'Sensor id'|trans }}</dt>
                                <dd class="col-sm-9 mission-sensor-id sensor-id"><div class="text-truncate" title="{{ sensor.id }}">{{ sensor.id }}</div>
                                </dd>

                                <dt class="col-sm-3 mission-sensor-identifier sensor-identifier">{{ 'Identifier'|trans }}</dt>
                                <dd class="col-sm-9 mission-sensor-identifier sensor-identifier">{{ sensor.identifier|default(missing_value) }}</dd>

                                <dt class="col-sm-3 mission-sensor-observation-type sensor-observation-type">{{ 'Observation type'|trans }}</dt>
                                <dd class="col-sm-9 mission-sensor-observation-type sensor-observation-type">{{ sensor.observationType ? sensor.observationType|trans : missing_value }}</dd>

                                {% if sensor.qoi|default(false) %}
                                    <dt class="col-sm-3 mission-sensor-qio sensor-qio">{{ 'Quality of information'|trans }}</dt>
                                    <dd class="col-sm-9 mission-sensor-qio sensor-qio">
                                        {{ render_qoi(sensor.qoi) }}
                                    </dd>
                                {% endif %}
                            </dl>
                        </div>
                    </div>
                </div>

                {{ form_widget(form) }}

                <div class="row border-top pt-3">
                    <div class="col">
                        {% if delete_form|default(false) %}
                            {# TODO: Make this button do what it says. #}
                            <button id="delete-form-submit" type="button" class="btn btn-danger">{{ 'Remove sensor from mission'|trans }}</button>
                        {% endif %}
                    </div>
                    <div class="col-auto ml-auto">
                        <a class="btn btn-dark mr-3" href="{{ path_from_referer('mission_show', {id: mission_sensor.mission.id}) }}">{{ 'Cancel'|trans }}</a>
                        <button class="btn btn-success px-md-5">{{ is_new_sensor ? 'Create'|trans : 'Update'|trans }}</button>
                    </div>
                </div>
            {{ form_end(form) }}

            {% if delete_form|default(false) %}
                {{ form_start(delete_form, {attr: { id: 'delete-form' }}) }}
                    <input type="hidden" name="_token" value="{{ csrf_token('delete'~mission_sensor.id) }}"/>
                {{ form_end(delete_form) }}

                <script>
                    document.getElementById('delete-form-submit').addEventListener('click', function () {
                        if (confirm({{ 'Confirm that you want to remove this sensor from the mission.'|trans|json_encode|raw }})) {
                            document.getElementById('delete-form').submit();
                        }
                    })
                </script>

            {% endif %}
        </article>
    </div>
{% endblock %}


{% block stylesheets %}
    {#{ parent() }#}
    {{ encore_entry_link_tags('mission_sensor/edit') }}
{% endblock %}

{% block javascripts %}
    {#{ parent() }#}
    {{ encore_entry_script_tags('mission_sensor/edit') }}
{% endblock %}

templates/mission_sensor/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'Mission sensors'|trans }}{% endblock %}

{% block body %}
    <h1>{{ 'Mission sensors'|trans }}</h1>

    <table class="table">
        <thead>
            <tr>
                <th>{{ 'Name'|trans }}</th>
                <th>{{ 'Sensor'|trans }}</th>
                <th>{{ 'Enabled'|trans }}</th>
                <th>{{ 'Added at'|trans }}</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for mission_sensor in mission_sensors %}
            <tr>
                <td>{{ mission_sensor.name }}</td>
                <td>{{ mission_sensor.sensor }}</td>
                <td>{{ mission_sensor.enabled ? 'Yes'|trans : 'No'|trans }}</td>
                <td>{{ mission_sensor.createdAt|date }}</td>
                <td>
                    <a href="{{ path_with_referer('mission_sensor_edit', {mission: mission_sensor.mission.id, id: mission_sensor.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path_with_referer('mission_sensor_add', {mission: mission.id}) }}">{{ 'Add mission sensor'|trans }}</a>
{% endblock %}

templates/mission_sensor/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'Add mission sensor'|trans }}{% endblock %}

{% block body %}
    <h1>{{ 'Add mission sensor'|trans }}</h1>

    {{ include('mission_sensor/_form.html.twig') }}

    <a href="{{ path('mission_sensor_index', {mission: mission_sensor.mission.id}) }}">{{ 'Cancel'|trans }}</a>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('mission_sensor/new') }}
{% endblock %}

templates/mission_sensor/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'Mission sensor'|trans }}{% endblock %}

{% block body %}
    <h1>{{ 'Mission sensor'|trans }}</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Name</th>
                <td>{{ mission_sensor.name }}</td>
            </tr>
            <tr>
                <th>Sensor</th>
                <td>{{ mission_sensor.sensor }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('mission_sensor_index', {mission: mission_sensor.mission.id}) }}">back to list</a>

    <a href="{{ path('mission_sensor_edit', {mission: mission_sensor.mission.id, id: mission_sensor.id}) }}">edit</a>

    {{ include('mission_sensor/_delete_form.html.twig') }}
{% endblock %}